### ISSUE TITLE
Do not build docker container for docs and example changes

### ISSUE THREAD

**Issue by hekike** [openmeterio/openmeter#93]
We could be more selective with container builds and skip them for docs and example changes.
Benefits:

- faster builds
- less noise in container registry

**Comment by sagikazarmark** [comment]
CI runs are under 5 minutes which IMO is acceptable.

> faster builds

General build/test/lint steps are around ~3 minutes. Container builds are 3 to 5 minutes. We only gain anything if we disable CI all together for those paths.

> less noise in container registry

Images built by PR triggers are not pushed to the registry anyway.

The problem with running CI selectively, is that we also have to disable required checks, because they apply to PRs universally.

From this perspective, waiting 5 minutes for each PR to become green is not a high price to pay IMO.

(You can always ignore those if absolutely necessary and merge PRs bypassing checks.)

**Comment by hekike** [comment]
Okay, makes sense. Thanks for highlighting the tradeoffs. Closing it.
